[project]
name = ""
version = "0.1.0"
description = "Twelve"
readme = "README.md"
requires-python = "~=3.11"
dependencies = [
    "aiocache~=0.12.2",
    "backoff~=2.2",
    "nonebot2[fastapi,httpx,websockets]~=2.2",
    "nonebot-adapter-onebot~=2.3",
    "nonebot-plugin-alconna~=0.36,<0.37",
    "nonebot-plugin-apscheduler~=0.3",
    "nonebot-plugin-htmlrender~=0.2",
    "nonebot-plugin-orm[default]~=0.7",
    "nonebot-plugin-sentry~=1.0",
    "nonebot-plugin-session~=0.2",
    "nonebot-plugin-session-orm~=0.1",
    "pydantic~=1.10",
]

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
]
plugins = [
    "nonebot_plugin_alconna",
    "nonebot_plugin_apscheduler",
    "nonebot_plugin_htmlrender",
    "nonebot_plugin_orm",
    "nonebot_plugin_sentry",
    "nonebot_plugin_session",
    "nonebot_plugin_session_orm",
]
plugin_dirs = ["src/plugins"]
builtin_plugins = []

[tool.pdm.dev-dependencies]
dev = ["black~=23.11", "isort~=5.12", "nonebot-plugin-orm[sqlite]~=0.7"]

[tool.pyright]
enableExperimentalFeatures = true
pythonVersion = "3.11"
pythonPlatform = "Linux"
