"""initial revision

迁移 ID: 770b97dd5299
父迁移: 
创建时间: 2023-11-18 04:43:41.481381

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "770b97dd5299"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("live",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "live_subscription",
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["nonebot_plugin_session_orm_sessionmodel.id"],
            name=op.f(
                "fk_live_subscription_session_id_nonebot_plugin_session_orm_sessionmodel"
            ),
        ),
        sa.PrimaryKeyConstraint("uid", "session_id", name=op.f("pk_live_subscription")),
        info={"bind_key": "live"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("live_subscription")
    # ### end Alembic commands ###
