"""drop session

迁移 ID: dccfaa3f1034
父迁移: b49551286716
创建时间: 2025-07-14 01:30:10.596342

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dccfaa3f1034"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = "97b890d49c65", "4b59404e5d2c"


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_session_orm_sessionmodel")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_session_orm_sessionmodel",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("bot_id", sa.VARCHAR(length=64), nullable=False),
        sa.Column("bot_type", sa.VARCHAR(length=32), nullable=False),
        sa.Column("platform", sa.VARCHAR(length=32), nullable=False),
        sa.Column("level", sa.INTEGER(), nullable=False),
        sa.Column("id1", sa.VARCHAR(length=64), nullable=False),
        sa.Column("id2", sa.VARCHAR(length=64), nullable=False),
        sa.Column("id3", sa.VARCHAR(length=64), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_nonebot_plugin_session_orm_sessionmodel")
        ),
        sa.UniqueConstraint(
            "bot_id",
            "bot_type",
            "platform",
            "level",
            "id1",
            "id2",
            "id3",
            name=op.f("nonebot_plugin_session_orm_unique_session"),
        ),
    )
    # ### end Alembic commands ###
